Instalar paquetote

In [1]:
#pip install simfin

Documentación: https://github.com/SimFin/simfin

Tutorial: https://github.com/SimFin/simfin-tutorials/blob/master/03_Growth_Returns.ipynb

Once the simfin package has been installed and you got your API-key, the following Python program will automatically download all Income Statements for US companies, and print the Revenue and Net Income for Microsoft.

In [ ]:
# api key 1: a96c6611-3bd8-4c8a-935b-27b5a2dee1d1 ## 10 minute mail basura, sin suscripción

In [2]:
import simfin as sf
from simfin.names import *

In [3]:
# Set your API-key for downloading data.
# Replace YOUR_API_KEY with your actual API-key.
sf.set_api_key('a96c6611-3bd8-4c8a-935b-27b5a2dee1d1')

In [4]:
# Set the local directory where data-files are stored.
# The dir will be created if it does not already exist.
sf.set_data_dir('~/simfin_data/')

In [5]:
# Load the annual Income Statements for all companies in the US.
# The data is automatically downloaded if you don't have it already.

#df = sf.load_income(variant='annual', market='us')
#sf.load_cashflow
df = sf.load_income(variant='quarterly', market='us')

Dataset "us-income-quarterly" not on disk.
- Downloading ... 100.0%
- Extracting zip-file ... Done!
- Loading from disk ... Done!

In [11]:
df

                    SimFinId Currency  Fiscal Year Fiscal Period Publish Date  \
Ticker Report Date
A      2017-10-31      45846      USD         2017            Q4   2017-12-21
       2018-01-31      45846      USD         2018            Q1   2018-03-06
       2018-04-30      45846      USD         2018            Q2   2018-05-31
       2018-07-31      45846      USD         2018            Q3   2018-08-30
       2018-10-31      45846      USD         2018            Q4   2018-12-20
...                      ...      ...          ...           ...          ...
ZYXI   2021-09-30     171401      USD         2021            Q3   2021-11-02
       2021-12-31     171401      USD         2021            Q4   2022-03-22
       2022-03-31     171401      USD         2022            Q1   2022-04-28
       2022-06-30     171401      USD         2022            Q2   2022-07-28
       2022-09-30     171401      USD         2022            Q3   2022-10-27

                   Restated Date  Shares (Basic)  Shares (Diluted)  \
Ticker Report Date
A      2017-10-31     2018-12-20     324000000.0       327000000.0
       2018-01-31     2019-03-05     323000000.0       323000000.0
       2018-04-30     2019-05-30     322000000.0       326000000.0
       2018-07-31     2018-08-30     320000000.0       324000000.0
       2018-10-31     2020-12-18     319000000.0       327000000.0
...                          ...             ...               ...
ZYXI   2021-09-30     2022-10-27      38244800.0        39042300.0
       2021-12-31     2022-10-27      34167100.0        36325300.0
       2022-03-31     2023-04-27      42252100.0        43087000.0
       2022-06-30     2023-07-27      38851000.0        39893000.0
       2022-09-30     2022-10-27      38046000.0        38865000.0

                         Revenue  Cost of Revenue  ...  \
Ticker Report Date                                 ...
A      2017-10-31   1.189000e+09     -542000000.0  ...
       2018-01-31   1.211000e+09     -541000000.0  ...
       2018-04-30   1.206000e+09     -563000000.0  ...
       2018-07-31   1.203000e+09     -542000000.0  ...
       2018-10-31   1.294000e+09     -592000000.0  ...
...                          ...              ...  ...
ZYXI   2021-09-30   3.478600e+07       -6837000.0  ...
       2021-12-31   4.036600e+07       -7331000.0  ...
       2022-03-31   3.108300e+07       -6921000.0  ...
       2022-06-30   3.675900e+07       -7305000.0  ...
       2022-09-30   4.152000e+07       -8391000.0  ...

                    Non-Operating Income (Loss)  Interest Expense, Net  \
Ticker Report Date
A      2017-10-31                    -7000000.0            -13000000.0
       2018-01-31                     4000000.0            -11000000.0
       2018-04-30                    17000000.0             -9000000.0
       2018-07-31                    17000000.0             -9000000.0
       2018-10-31                    19000000.0             -8000000.0
...                                         ...                    ...
ZYXI   2021-09-30                      -18000.0               -18000.0
       2021-12-31                      -23000.0               -23000.0
       2022-03-31                     -124000.0              -124000.0
       2022-06-30                     -115000.0              -115000.0
       2022-09-30                     -106000.0              -106000.0

                    Pretax Income (Loss), Adj.  Abnormal Gains (Losses)  \
Ticker Report Date
A      2017-10-31                  226000000.0                      NaN
       2018-01-31                  233000000.0                      NaN
       2018-04-30                  227000000.0                      NaN
       2018-07-31                  242000000.0                      NaN
       2018-10-31                  244000000.0                      NaN
...                                        ...                      ...
ZYXI   2021-09-30                    8028000.0                      NaN
       2021-12-31                   11563000.0                      NaN
       2022-03-31                    1782000.0                 200000.0
       2022-06-30                    4249000.0                -100000.0
       2022-09-30                    6452000.0                -100000.0

                    Pretax Income (Loss)  Income Tax (Expense) Benefit, Net  \
Ticker Report Date
A      2017-10-31              226000000                        -49000000.0
       2018-01-31              233000000                       -553000000.0
       2018-04-30              227000000                        -22000000.0
       2018-07-31              242000000                         -6000000.0
       2018-10-31              244000000                        -49000000.0
...                                  ...                                ...
ZYXI   2021-09-30                8028000                         -1921000.0
       2021-12-31               11563000                         -2669000.0
       2022-03-31                1982000                          -605000.0
       2022-06-30                4149000                          -803000.0
       2022-09-30                6352000                         -1479000.0

                    Income (Loss) from Continuing Operations  \
Ticker Report Date
A      2017-10-31                                  177000000
       2018-01-31                                 -320000000
       2018-04-30                                  205000000
       2018-07-31                                  236000000
       2018-10-31                                  195000000
...                                                      ...
ZYXI   2021-09-30                                    6107000
       2021-12-31                                    8894000
       2022-03-31                                    1377000
       2022-06-30                                    3346000
       2022-09-30                                    4873000

                    Net Extraordinary Gains (Losses)  Net Income  \
Ticker Report Date
A      2017-10-31                                NaN   177000000
       2018-01-31                                NaN  -320000000
       2018-04-30                                NaN   205000000
       2018-07-31                                NaN   236000000
       2018-10-31                                NaN   195000000
...                                              ...         ...
ZYXI   2021-09-30                                NaN     6107000
       2021-12-31                                NaN     8894000
       2022-03-31                                NaN     1377000
       2022-06-30                                NaN     3346000
       2022-09-30                                NaN     4873000

                    Net Income (Common)
Ticker Report Date
A      2017-10-31             177000000
       2018-01-31            -320000000
       2018-04-30             205000000
       2018-07-31             236000000
       2018-10-31             195000000
...                                 ...
ZYXI   2021-09-30               6107000
       2021-12-31               8894000
       2022-03-31               1377000
       2022-06-30               3346000
       2022-09-30               4873000

[61477 rows x 26 columns]

In [9]:
df.shape

(61477, 26)

In [6]:
# Print all Revenue and Net Income for Microsoft (ticker MSFT).
print(df.loc['MSFT', [REVENUE, NET_INCOME]])

                  Revenue   Net Income
Report Date
2017-12-31   2.891800e+10  -6302000000
2018-03-31   2.681900e+10   7424000000
2018-06-30   3.008500e+10   8873000000
2018-09-30   2.908400e+10   8824000000
2018-12-31   3.247100e+10   8420000000
2019-03-31   3.057100e+10   8809000000
2019-06-30   3.371700e+10  13187000000
2019-09-30   3.305500e+10  10678000000
2019-12-31   3.690600e+10  11649000000
2020-03-31   3.502100e+10  10752000000
2020-06-30   3.803300e+10  11202000000
2020-09-30   3.715400e+10  13893000000
2020-12-31   4.307600e+10  15463000000
2021-03-31   4.170600e+10  15457000000
2021-06-30   4.615200e+10  16458000000
2021-09-30   4.531700e+10  20505000000
2021-12-31   5.172800e+10  18765000000
2022-03-31   4.936000e+10  16728000000
2022-06-30   5.186500e+10  16740000000
2022-09-30   5.012200e+10  17556000000